version: '3.3'

services:

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - network42
    restart: on-failure

  nginx:
    build: requirements/nginx
    container_name: nginx
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - network42
    restart: on-failure

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysqld
    networks:
      - network42
    restart: on-failure


volumes:
  wordpress:
  nginx:
  mariadb:

networks:
  network42:
